/*
 * This code was generated by FormatTemplate as part of the build process. Do not edit it.
 *
 * Generated on 2017-02-27 10:24:01.
 *
 */

internal static class BuildInfo {
    internal const string Configuration = "Debug";

    internal const bool IsDebug =
#if DEBUG
        true;
#else
        false;
#endif

    internal const bool IsCLR2 =
#if CLR2
        true;
#else
        false;
#endif

    internal const bool IsCLR4 =
#if CLR4
        true;
#else
        false;
#endif

    internal const bool IsSilverlight =
#if SILVERLIGHT
        true;
#else
        false;
#endif
}